//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.r_eg.MvsSlnTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SlnSamplesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlnSamplesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.r_eg.MvsSlnTest.SlnSamplesResource", typeof(SlnSamplesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.26228.4
        ///MinimumVisualStudioVersion = 10.0.30319.1
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;root&quot;, &quot;root&quot;, &quot;{571DA510-79F7-48C0-9024-9632E16353DF}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		.gitignore = .gitignore
        ///		.version = .version
        ///		build.bat = build.bat
        ///		changelog.txt = changelog.txt
        ///		gnt.core = gnt.core
        ///		LICENSE = LICENSE
        ///		packages.config = packages.config
        ///		Readme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string regXwild {
            get {
                return ResourceManager.GetString("regXwild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 14
        ///VisualStudioVersion = 14.0.25420.1
        ///MinimumVisualStudioVersion = 10.0.30319.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;CIMLib&quot;, &quot;CIMLib\CIMLib.csproj&quot;, &quot;{A7BF1F9C-F18D-423E-9354-859DC3CFAFD4}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;vsSolutionBuildEvent&quot;, &quot;vsSolutionBuildEvent\vsSolutionBuildEvent.csproj&quot;, &quot;{32E44995-F621-4E77-B46A-8F65D64E7FEA}&quot;
        ///	ProjectSection(ProjectDependencies) = pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vsSolutionBuildEvent {
            get {
                return ResourceManager.GetString("vsSolutionBuildEvent", resourceCulture);
            }
        }
    }
}
