//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvsSlnTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SlnSamplesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlnSamplesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvsSlnTest.SlnSamplesResource", typeof(SlnSamplesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 14
        ///VisualStudioVersion = 14.0.25420.1
        ///MinimumVisualStudioVersion = 10.0.30319.1
        ///Global
        /// GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///  CI.Debug.net45|Any.CPU.etc = CI.Debug.net45|Any.CPU.etc
        ///  CI.Debug|Any.CPU.etc = CI.Debug|Any.CPU.etc
        ///  CI.Release.net45|Any.CPU.etc = CI.Release.net45|Any.CPU.etc
        ///  CI.Release|Any.CPU.etc = CI.Release|Any.CPU.etc
        ///  Debug.net45|Any.CPU.etc = Debug.net45|Any.CPU.etc
        ///  Debug.x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfNamesDots {
            get {
                return ResourceManager.GetString("ConfNamesDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.28307.329
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;ConsoleApp1&quot;, &quot;ConsoleApp1\ConsoleApp1.csproj&quot;, &quot;{20FD5406-C998-4926-956F-5779766D7C31}&quot;
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;ClassLibrary1&quot;, &quot;ClassLibrary1\ClassLibrary1.csproj&quot;, &quot;{3D3E87AF-22F7-4E26-937F-AA430BCA2942}&quot;
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;Cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtensibilityGlobals {
            get {
                return ResourceManager.GetString("ExtensibilityGlobals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.26228.4
        ///MinimumVisualStudioVersion = 10.0.30319.1
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;root&quot;, &quot;root&quot;, &quot;{571DA510-79F7-48C0-9024-9632E16353DF}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		.gitignore = .gitignore
        ///		.version = .version
        ///		build.bat = build.bat
        ///		changelog.txt = changelog.txt
        ///		gnt.core = gnt.core
        ///		LICENSE = LICENSE
        ///		packages.config = packages.config
        ///		Readme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string regXwild {
            get {
                return ResourceManager.GetString("regXwild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///VisualStudioVersion = 14.0.25420.1
        ///MinimumVisualStudioVersion = 10.0.30319.1.
        /// </summary>
        internal static string Section_Header {
            get {
                return ResourceManager.GetString("Section_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///		{A7BF1F9C-F18D-423E-9354-859DC3CFAFD4}.CI_Debug_net45|Any CPU.ActiveCfg = Release_net45|Any CPU
        ///		{A7BF1F9C-F18D-423E-9354-859DC3CFAFD4}.CI_Debug_net45|Any CPU.Build.0 = Release_net45|Any CPU
        ///		{A7BF1F9C-F18D-423E-9354-859DC3CFAFD4}.CI_Debug|Any CPU.ActiveCfg = Release|Any CPU
        ///		{32E44995-F621-4E77-B46A-8F65D64E7FEA}.CI_Release_net45|Any CPU.ActiveCfg = CI_Release_net45|Any CPU
        ///		{32E44995-F621-4E77-B46A-8F65D64E7FEA}.CI_Release_net45|Any C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Section_Prj_Config {
            get {
                return ResourceManager.GetString("Section_Prj_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;Bridge&quot;, &quot;Bridge\Bridge.csproj&quot;, &quot;{73919171-44B6-4536-B892-F1FCA653887C}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;CIMLib&quot;, &quot;CIMLib\CIMLib.csproj&quot;, &quot;{A7BF1F9C-F18D-423E-9354-859DC3CFAFD4}&quot;
        ///	ProjectSection(ProjectDependencies) = postProject
        ///		{73919171-44B6-4536-B892-F1FCA653887C} = {73919171-44B6-4536-B892-F1FCA653887C}
        ///		{4F8BB8CD-1116-4F07-9B8F-06D69FB8589B} = {4F8BB8CD-1116-4F07-9B8F-06D69FB8589B}
        ///	EndProjectSection
        ///EndPro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Section_Project_Dep {
            get {
                return ResourceManager.GetString("Section_Project_Dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		CI_Debug_net45|Any CPU = CI_Debug_net45|Any CPU
        ///		CI_Debug|Any CPU = CI_Debug|Any CPU
        ///		CI_Release_net45|Any CPU = CI_Release_net45|Any CPU
        ///		CI_Release|x86 = CI_Release|x86
        ///		Debug_net45|Any CPU = Debug_net45|Any CPU
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release_net45|Any CPU = Release_net45|Any CPU
        ///		Release|x64 = Release|x64
        ///	EndGlobalSection.
        /// </summary>
        internal static string Section_Sln_Config {
            get {
                return ResourceManager.GetString("Section_Sln_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;.gnt&quot;, &quot;.gnt&quot;, &quot;{65FF5D56-E814-4956-89BD-7C53EC557BFE}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		.gnt\gnt.core = .gnt\gnt.core
        ///		.gnt\packages.config = .gnt\packages.config
        ///	EndProjectSection
        ///EndProject
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;tools&quot;, &quot;tools&quot;, &quot;{849DD790-F856-493C-A19E-2560A21F6AF1}&quot;
        ///	ProjectSection(SolutionItems) = preProject
        ///		tools\gnt.bat = tools\gnt.bat
        ///	EndProjectSection
        ///EndProject.
        /// </summary>
        internal static string Section_Sln_Items {
            get {
                return ResourceManager.GetString("Section_Sln_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	GlobalSection(ExtensibilityGlobals) = postSolution
        ///		SolutionGuid = {B3244B90-20DE-4D69-8692-EBC686503F90}
        ///		SomeOtherEmptyData = 
        ///		SomeNullData
        ///		EnterpriseLibraryConfigurationToolBinariesPath = packages\Conari.1.3.0\lib\NET40;packages\vsSBE.CI.MSBuild\bin
        ///	EndGlobalSection.
        /// </summary>
        internal static string Section_WExtensibilityGlobals_Test {
            get {
                return ResourceManager.GetString("Section_WExtensibilityGlobals_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	GlobalSection(NestedProjects) = preSolution
        ///		{BEB7D6F5-5065-4427-9797-2AD7511862D8} = {8B05CE1C-999E-460D-80FF-E44DFEC019E7}
        ///		{1257C186-1EC7-41C6-9344-14B2341BE6F6} = {BEB7D6F5-5065-4427-9797-2AD7511862D8}
        ///		{80AEF083-D86A-416E-88B8-300DF20399AF} = {8B05CE1C-999E-460D-80FF-E44DFEC019E7}
        ///	EndGlobalSection.
        /// </summary>
        internal static string Section_WNestedProjects_Test2 {
            get {
                return ResourceManager.GetString("Section_WNestedProjects_Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	GlobalSection(NestedProjects) = preSolution
        ///		{A2D23001-08A8-49AF-A975-64ADA41EB08A} = {1257C186-1EC7-41C6-9344-14B2341BE6F6}
        ///		{C4C66B30-66CD-4D68-9A95-372CA4A13611} = {80AEF083-D86A-416E-88B8-300DF20399AF}
        ///		{C1A3BCC3-F120-471D-A31E-4B835A06F42D} = {BEB7D6F5-5065-4427-9797-2AD7511862D8}
        ///	EndGlobalSection.
        /// </summary>
        internal static string Section_WNestedProjects_Test3 {
            get {
                return ResourceManager.GetString("Section_WNestedProjects_Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	GlobalSection(NestedProjects) = preSolution
        ///		{BEB7D6F5-5065-4427-9797-2AD7511862D8} = {8B05CE1C-999E-460D-80FF-E44DFEC019E7}
        ///		{1257C186-1EC7-41C6-9344-14B2341BE6F6} = {BEB7D6F5-5065-4427-9797-2AD7511862D8}
        ///		{80AEF083-D86A-416E-88B8-300DF20399AF} = {8B05CE1C-999E-460D-80FF-E44DFEC019E7}
        ///		{A2D23001-08A8-49AF-A975-64ADA41EB08A} = {1257C186-1EC7-41C6-9344-14B2341BE6F6}
        ///		{C4C66B30-66CD-4D68-9A95-372CA4A13611} = {80AEF083-D86A-416E-88B8-300DF20399AF}
        ///		{C1A3BCC3-F120-471D-A31E-4B835A06F42D} = {BEB7D6F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Section_WNestedProjects_Test4 {
            get {
                return ResourceManager.GetString("Section_WNestedProjects_Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.28307.329
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;ConsoleApp1&quot;, &quot;ConsoleApp1\ConsoleApp1.csproj&quot;, &quot;{20FD5406-C998-4926-956F-5779766D7C31}&quot;
        ///EndProject
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;dir1&quot;, &quot;dir1&quot;, &quot;{1571A74C-579F-4C91-8484-322B7D89B430}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;ClassLibrary1&quot;, &quot;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolutionFoldersAndProjects {
            get {
                return ResourceManager.GetString("SolutionFoldersAndProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 14
        ///VisualStudioVersion = 14.0.25420.1
        ///MinimumVisualStudioVersion = 10.0.30319.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;CIMLib&quot;, &quot;CIMLib\CIMLib.csproj&quot;, &quot;{A7BF1F9C-F18D-423E-9354-859DC3CFAFD4}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;vsSolutionBuildEvent&quot;, &quot;vsSolutionBuildEvent\vsSolutionBuildEvent.csproj&quot;, &quot;{32E44995-F621-4E77-B46A-8F65D64E7FEA}&quot;
        ///	ProjectSection(ProjectDependencies) = pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vsSolutionBuildEvent {
            get {
                return ResourceManager.GetString("vsSolutionBuildEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinimumVisualStudioVersion = 10.0.30319.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;Provider&quot;, &quot;Provider\Provider.csproj&quot;, &quot;{4F8BB8CD-1116-4F07-9B8F-06D69FB8589B}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;vsSolutionBuildEvent&quot;, &quot;vsSolutionBuildEvent\vsSolutionBuildEvent.csproj&quot;, &quot;{32E44995-F621-4E77-B46A-8F65D64E7FEA}&quot;
        ///	ProjectSection(ProjectDependencies) = postProject
        ///		{4F8BB8CD-1116-4F07-9B8F-06D69FB8589B} = {4F8BB8CD-1116-4F07-9B8F-06D69FB8589B}
        ///	EndProjectSection [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vsSolutionBuildEvent_map {
            get {
                return ResourceManager.GetString("vsSolutionBuildEvent_map", resourceCulture);
            }
        }
    }
}
